// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfudqCcyP8BXHNNo8SgWGDpAQ9C4v3b1M',
    appId: '1:969564036970:web:516a0249f314a8a4c3cf13',
    messagingSenderId: '969564036970',
    projectId: 'current-da96c',
    authDomain: 'current-da96c.firebaseapp.com',
    storageBucket: 'current-da96c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNeGB2eFXivW9PB4IJieI18DIKj9g2og',
    appId: '1:969564036970:android:50121060d054f09bc3cf13',
    messagingSenderId: '969564036970',
    projectId: 'current-da96c',
    storageBucket: 'current-da96c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SdgAhVutxBilt4wgHMxg_vhmWAnYxhs',
    appId: '1:969564036970:ios:e6cc249348a22b30c3cf13',
    messagingSenderId: '969564036970',
    projectId: 'current-da96c',
    storageBucket: 'current-da96c.appspot.com',
    iosClientId: '969564036970-8l0hlmqhm8bm1vtnpmd081777n5gip4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.currentVpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3SdgAhVutxBilt4wgHMxg_vhmWAnYxhs',
    appId: '1:969564036970:ios:e6cc249348a22b30c3cf13',
    messagingSenderId: '969564036970',
    projectId: 'current-da96c',
    storageBucket: 'current-da96c.appspot.com',
    iosClientId: '969564036970-8l0hlmqhm8bm1vtnpmd081777n5gip4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.currentVpn',
  );
}
